version: "3"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    environment:
      - xpack.security.enabled=false
    ports:
      - 5601:5601

  filebeat:
    depends_on:
      - elasticsearch
      - logstash
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/logs

  logstash:
    depends_on:
      - elasticsearch
    build: # we build a custom image because we want to test the truncate plugin
      context: ./logstash
      args:
        - ELK_VERSION=${ELK_VERSION}
    image: elk_customized_logstash:${ELK_VERSION}      
    #image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    environment:
      - log.level=info
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

volumes:
  esdata:
    driver: local
