filebeat.prospectors:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /logs/*.log
  tags: ["test-tag", "another-tag"]
  fields_under_root: true
  fields:
    env: dev
  json.keys_under_root: true # enable json parsing
  json.overwrite_keys: true
  json.add_error_key: true
  json.message_key: msg

processors:
 - drop_fields:
     fields: ["prospector.type", "beat.name", "beat.version", "beat.hostname", "offset", "source"]

setup.dashboards.enabled: true
setup.kibana:
  host: "http://kibana:5601"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

# output.console:
#   pretty: true
